### ISSUE TITLE
Exporting columns that are defined by ComponentRenderer

### ISSUE THREAD

**Issue by josegulisano** [xdev-software/vaadin-grid-exporter#113]
I have several grid columns that have custom renderers
Column myColumn = this.addColumn(new ComponentRenderer<>(this::createUserNumber))

These columns do not get included in the export. Is there a way to configure the exporter to include these values as part of the export?

**Comment by AB-xdev** [comment]
At fist: The code that extracts the data from the Grid can be found [here](https://github.com/xdev-software/vaadin-grid-exporter/blob/develop/vaadin-grid-exporter/src/main/java/software/xdev/vaadin/grid_exporter/grid/GridDataExtractor.java).

Currently we support ValueProviders and simple renderers.

These are normally sufficient to extract the required data because other renderers usually very specific components (e.g. charts or buttons) that can't be printed.

I don't know what ``createUserNumber`` is doing exactly but if it's just displaying a Number as a String you can also use a Valueprovider or TextRenderer.

The other alternative that might work would be a hidden column that contains the "unrendered" value.

**Comment by josegulisano** [comment]
I was able to make it work with a "hidden" column.

The column I was having trouble with is a hyperlinked cell in the grid.  I am using a ComponentRenderer to render the Anchor:

```
Column myColumn = this.addColumn(new ComponentRenderer<>(this::createUserNumber))

private Component createUserNumber(User user) {
        String route = RouteConfiguration.forSessionScope().getUrl(User.class, user.getId());
        Anchor anchor = new Anchor(route, userDetails.getId().toString());
            Tooltips.getCurrent().setTooltip(anchor, "View user details");
            return anchor;
}

```
Unless you have any other suggestions for creating the hyperlinked cell, I'll go with the hidden column option.

Thank you!
